"""Extend contact table

Revision ID: 1e178100901b
Revises: 1cb2e35c53a8
Create Date: 2025-05-31 20:37:15.321935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e178100901b'
down_revision: Union[str, None] = '1cb2e35c53a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column('contacts', sa.Column('avatar', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'avatar')
    op.drop_column('contacts', 'password')
    # ### end Alembic commands ###
