"""Add email verification

Revision ID: 3a2ef571ede1
Revises: e67bfab3217f
Create Date: 2025-06-01 20:28:07.892570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a2ef571ede1'
down_revision: Union[str, None] = 'e67bfab3217f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('verified', sa.Boolean(), nullable=False))
    op.add_column('contacts', sa.Column('verification_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'verification_token')
    op.drop_column('contacts', 'verified')
    # ### end Alembic commands ###
